#!/usr/bin/env python3
#
# This file is part of opsd.
#
# opsd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# opsd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with opsd.  If not, see <http://www.gnu.org/licenses/>.

"""Operations daemon for the Warwick one-metre telescope"""

# pylint: disable=invalid-name
# pylint: disable=broad-except
# pylint: disable=too-few-public-methods
# pylint: disable=too-many-branches
# pylint: disable=too-many-statements
# pylint: disable=too-many-instance-attributes

import datetime
import math
import threading
import time
import Pyro4
import warwick.observatory as observatory

# TODO: Convert to new backend when we are able to test
DOME_HOST = '192.168.0.102'
DOME_PORT = 9004
DOME_NAME = 'dome_daemon'
DOME_URI = 'PYRO:' + DOME_NAME + '@' + DOME_HOST + ':' + str(DOME_PORT)

# Communications timeout when using the status and heartbeat commands (should be instant)
DOME_PYRO_STATUSHEARTBEAT_TIMEOUT = 5

# Communications timeout when opening or closing the dome (takes up to ~80 seconds)
DOME_PYRO_OPENCLOSE_TIMEOUT = 120

# Delay between ops and dome loop ticks (seconds)
LOOP_DELAY = 10

# Timeout period (seconds) for the dome controller
# The dome heartbeat is pinged once per LOOP_DELAY when the dome is under
# automatic control and is fully open or fully closed.  This timeout should
# be large enough to account for the time it takes to open and close the dome
DOME_HEARTBEAT_TIMEOUT = 120

# This should be kept in sync with the dictionary in ops
class CommandStatus:
    """Numeric return codes"""
    # General error codes
    Succeeded = 0
    Failed = 1
    Blocked = 2
    InErrorState = 3

class OperationsMode:
    """Operational status"""
    Error, Automatic, Manual = range(3)
    Names = ['Error', 'Automatic', 'Manual']

class DomeStatus:
    """Dome status"""
    Closed, Open, Moving, Timeout = range(4)
    Names = ['Closed', 'Open', 'Moving', 'Timeout']

def ParseDomeStatus(status):
    """Parses the return value from dome.status() into a DomeStatus"""
    if status[4] <= 0:
        return DomeStatus.Timeout
    if status[1] == 0 and status[2] == 0:
        return DomeStatus.Closed
    elif status[1] == 1 and status[2] == 1:
        return DomeStatus.Open
    else:
        return DomeStatus.Moving

class DomeCommandStatus:
    """Numeric return codes"""
    # General error codes
    Succeeded = 0
    Failed = 1
    Blocked = 2
    HeartbeatTimedOut = 3
    HeartbeatCloseInProgress = 4
    EastShutterMustBeFullyOpen = 10

TEL_STOW_POSITION = (0.616, 0.405)
TEL_PARK_TIMEOUT = 60

class TelescopeIdleAction:
    """Default action that waits until another activity has been queued"""

    def __init__(self):
        self._next_activity = None

    def tick(self):
        """Run a step of the logic of this action"""
        if self._next_activity is not None:
            return self._next_activity

        return self    

    def notify_frame(self, headers):
        """Called immediately when a new frame is available"""
        pass

    def action_name(self):
        """Returns the name of this action for the UI"""
        return 'IDLE'

    def cancel(self):
        """Attempt to cancel the current action"""
        pass

class TelescopeErrorAction(TelescopeIdleAction):
    """Represents a telescope error state.
       Does nothing until explicitly cleared by the user"""

    def tick(self):
        """Run a step of the logic of this action"""
        return self

    def action_name(self):
        return 'ERROR'

class TelescopeDrivePowerAction(TelescopeIdleAction):
    def __init__(self, enable):
        self._enable = enable

    def tick(self):
        """Run a step of the logic of this action"""
        with observatory.daemons.onemetre_power.connect() as power:
            if not power.switch('telescope_80v', self._enable):
                print('failed to switch telescope drive power to ' + str(enable))
                return TelescopeErrorAction()

        return self._next_activity

class CameraStopAction(TelescopeIdleAction):
    def __init__(self, camera):
        self._camera = camera

    def tick(self):
        """Run a step of the logic of this action"""
        if self._camera == 'blue':
            daemon = observatory.daemons.onemetre_blue_camera
        elif self._camera == 'red':
            daemon = observatory.daemons.onemetre_red_camera
        else:
            print('invalid camera id ' + str(self._camera))
            return TelescopeErrorAction()

        with daemon.connect() as cam:
            cam.stop_sequence()

        return self._next_activity

class StowTelescopeAction:
    """Parks the telescope at the stow position and disables the power"""

    def tick(self):
        """Run a step of the logic of this action"""
        return sequence_activities([
            CameraStopAction('blue'),
            CameraStopAction('red'),
            TelescopeDrivePowerAction(enable=True),
            TelescopeSlewAction(TEL_STOW_POSITION),
            TelescopeDrivePowerAction(enable=False)])

        # Query telescope state
        with observatory.daemons.onemetre_telescope.connect() as tel:
            t = tel.report_status()
        with observatory.daemons.onemetre_power.connect() as power:
            drive_enabled = power.last_measurement()['telescope_80v']

        # Check if we are already parked
        delta_alt = TEL_STOW_POSITION[0] - t['alt']
        delta_az = TEL_STOW_POSITION[1] - t['az']
        if math.sqrt(delta_alt**2 + delta_az**2) > 0.001:
            with observatory.daemons.onemetre_telescope.connect(TEL_PARK_TIMEOUT) as tel:
                slew = tel.slew_altaz(TEL_STOW_POSITION[0], TEL_STOW_POSITION[1])
                if slew != 0:
                    raise Exception('failed to park telescope with code ' + str(slew))

    def notify_frame(self, headers):
        """Called immediately when a new frame is available"""
        # We're not interested in the cameras
        pass

    def action_name(self):
        return 'STOWING'

    def cancel(self):
        """Attempt to cancel the current action"""
        # Cannot be cancelled
        return False

class TryLock(object):
    """Helper object for use with `with` statements"""
    def __init__(self, lock):
        self._lock = lock
        self._locked = False

    def __enter__(self):
        self._locked = self._lock.acquire(False)
        return self._locked

    def __exit__(self, *args):
        if self._locked:
            self._lock.release()
            self._locked = False

class OperationsDaemon:
    """Daemon class that controls the overall observatory operations"""
    def __init__(self):
        self._command_lock = threading.Lock()

        self._observing = False

        # "public" interface for changing dome state
        self._dome_requested_mode = OperationsMode.Manual
        self._dome_requested_status = DomeStatus.Closed

        # internal dome state - take the lock writing or reading coherant state!
        self._dome_lock = threading.Lock()
        self._dome_mode = OperationsMode.Manual
        self._dome_status = DomeStatus.Closed
        self._dome_updated = datetime.datetime.utcnow()

        domeloop = threading.Thread(target=self.__dome_loop)
        domeloop.daemon = True
        domeloop.start()

        # environment state - take the lock before writing or reading coherant state!
        self._environment_lock = threading.Lock()
        self._environment_updated = datetime.datetime.utcnow()
        self._environment_safe = False

        # "public" interface for changing telescope state
        self._tel_requested_mode = OperationsMode.Manual

        # internal telescope state - take the lock writing or reading coherant state!
        self._tel_lock = threading.Lock()
        self._tel_mode = OperationsMode.Manual
        self._tel_updated = datetime.datetime.utcnow()

        telloop = threading.Thread(target=self.__tel_loop)
        telloop.daemon = True
        telloop.start()

        runloop = threading.Thread(target=self.__ops_loop)
        runloop.daemon = True
        runloop.start()

    def __dome_status(self, status):
        """Reports status back to the main thread in a thread-safe manner"""
        with self._dome_lock:
            self._dome_status = status
            self._dome_updated = datetime.datetime.utcnow()
            return status

    def __dome_mode(self, mode):
        """Reports status back to the main thread in a thread-safe manner"""
        with self._dome_lock:
            self._dome_mode = mode
            self._dome_updated = datetime.datetime.utcnow()
            return mode

    def __dome_loop(self):
        """Thread that controls dome opening/closing to match requested state"""
        while True:
            # Handle requests from the user to change between manual and automatic mode
            # Manual intervention is required to clear errors and return to automatic mode.
            # If an error does occur the dome heartbeat will timeout, and it will close itself.
            auto_failure = self._dome_mode == OperationsMode.Error and \
                self._dome_requested_mode == OperationsMode.Automatic

            if self._dome_requested_mode != self._dome_mode and not auto_failure:
                print('dome: changing mode from ' + OperationsMode.Names[self._dome_mode] + \
                    ' to ' + OperationsMode.Names[self._dome_requested_mode])

                try:
                    with Pyro4.Proxy(DOME_URI) as dome:
                        # pylint: disable=protected-access
                        dome._pyroTimeout = DOME_PYRO_STATUSHEARTBEAT_TIMEOUT
                        # pylint: enable=protected-access
                        if self._dome_requested_mode == OperationsMode.Automatic:
                            # TODO: Change this to lock to ops mode
                            ret = dome.configure_heartbeat(DOME_HEARTBEAT_TIMEOUT)
                            if ret == DomeCommandStatus.Succeeded:
                                self.__dome_mode(OperationsMode.Automatic)
                            else:
                                print('error: failed to switch dome to auto with error: ', ret)
                                self.__dome_mode(OperationsMode.Error)
                        else:
                            # Switch from auto or error state back to manual
                            with Pyro4.Proxy(DOME_URI) as dome:
                                # TODO: Change this to unlock from ops mode
                                # TODO: the dome daemon should disable the ops lock if it times out
                                ret = dome.configure_heartbeat(0)

                            if ret == DomeCommandStatus.Succeeded:
                                self.__dome_mode(OperationsMode.Manual)
                            else:
                                print('error: failed to switch dome to manual with error: ', ret)
                                self.__dome_mode(OperationsMode.Error)
                except Exception as e:
                    print('error: failed to communicate with the dome daemon: ', e)
                    self.__dome_mode(OperationsMode.Error)

            if self._dome_mode == OperationsMode.Automatic:
                try:
                    with Pyro4.Proxy(DOME_URI) as dome:
                        # pylint: disable=protected-access
                        dome._pyroTimeout = DOME_PYRO_STATUSHEARTBEAT_TIMEOUT
                        # pylint: enable=protected-access
                        status = self.__dome_status(ParseDomeStatus(dome.status()))
                        wants_status = self._dome_requested_status
                        print('dome: is ' +  DomeStatus.Names[status] + ' and wants to be ' + \
                            DomeStatus.Names[wants_status])

                        if status == DomeStatus.Timeout:
                            print('dome: detected heartbeat timeout!')
                            self.__dome_mode(OperationsMode.Error)
                        elif wants_status == DomeStatus.Closed and status == DomeStatus.Open:
                            print('dome: sending heartbeat ping before closing')
                            dome.ping_heartbeat()
                            print('dome: closing')
                            self.__dome_status(DomeStatus.Moving)
                            # pylint: disable=protected-access
                            dome._pyroTimeout = DOME_PYRO_OPENCLOSE_TIMEOUT
                            ret = dome.close_shutters(east=True, west=True)
                            dome._pyroTimeout = DOME_PYRO_STATUSHEARTBEAT_TIMEOUT
                            # pylint: enable=protected-access
                            if ret == DomeCommandStatus.Succeeded:
                                self.__dome_status(DomeStatus.Closed)
                            else:
                                self.__dome_mode(OperationsMode.Error)
                        elif wants_status == DomeStatus.Open and status == DomeStatus.Closed:
                            print('dome: sending heartbeat ping before opening')
                            dome.ping_heartbeat()
                            print('dome: opening')
                            self.__dome_status(DomeStatus.Moving)
                            # pylint: disable=protected-access
                            dome._pyroTimeout = DOME_PYRO_OPENCLOSE_TIMEOUT
                            ret = dome.open_shutters(east=True, west=True)
                            dome._pyroTimeout = DOME_PYRO_STATUSHEARTBEAT_TIMEOUT
                            # pylint: enable=protected-access
                            if ret == DomeCommandStatus.Succeeded:
                                self.__dome_status(DomeStatus.Open)
                            else:
                                self.__dome_mode(OperationsMode.Error)
                        elif status == wants_status:
                            print('dome: sending heartbeat ping')
                            dome.ping_heartbeat()
                except Exception as e:
                    print('error: failed to communicate with the dome daemon: ', e)
                    self.__dome_mode(OperationsMode.Error)

            time.sleep(LOOP_DELAY)

    def __tel_mode(self, mode):
        """Sets the telescope mode in a thread-safe manner"""
        with self._tel_lock:
            self._tel_mode = mode
            self._tel_updated = datetime.datetime.utcnow()
            return mode

    def __tel_loop(self):
        while True:
            # Handle requests from the user to change between manual and automatic mode
            # Manual intervention is required to clear errors and return to automatic mode.
            auto_failure = self._tel_mode == OperationsMode.Error and \
                self._tel_requested_mode == OperationsMode.Automatic

            if self._tel_requested_mode != self._tel_mode and not auto_failure:
                print('tel: changing mode from ' + OperationsMode.Names[self._tel_mode] + \
                    ' to ' + OperationsMode.Names[self._tel_requested_mode])
                self.__tel_mode(self._tel_requested_mode)

            if self._tel_mode == OperationsMode.Automatic:
                try:
                    print('before tick')
                    test = StowTelescopeAction()
                    
                    test = run_actions(test)
                    test.tick()
                    print('after tick')
                    self._tel_requested_mode = OperationsMode.Manual
                except Exception as e:
                    print('error: telescope controller: ', e)
                    self._tel_mode(OperationsMode.Error)

            time.sleep(LOOP_DELAY)

    def __environment_safe(self, safe):
        """Reports status back to the main thread in a thread-safe manner"""
        with self._environment_lock:
            self._environment_safe = safe
            self._environment_updated = datetime.datetime.utcnow()
            return safe

    def __ops_loop(self):
        """Main operations run loop."""
        environment_safe = False
        while True:
            was_safe = environment_safe
            try:
                with observatory.daemons.onemetre_environment.connect() as environment:
                    status = environment.status()
                environment_safe = status['can_observe']
                if was_safe and not environment_safe:
                    observatory.log.warning('opsd', 'Environment has become unsafe')
                elif not was_safe and environment_safe:
                    observatory.log.info('opsd', 'Environment trigger timed out')
            except Exception as e:
                environment_safe = False
                print('error: failed to query environment: ', e)
                observatory.log.info('opsd', 'Failed to query environmentd (' + str(e) + ')')

            self.__environment_safe(environment_safe)
            if self._dome_requested_status == DomeStatus.Open and not environment_safe:
                print('closing dome due to environment alert')
                print('environment status is:')
                print(status)

            # Cancel observing if the weather turns bad
            if not environment_safe and self._observing:
                self._observing = False
                observatory.log.info('opsd', 'Observing condition automatically disabled')

            self._dome_requested_status = DomeStatus.Open if self._observing else DomeStatus.Closed

            # Check for requested status changes
            time.sleep(LOOP_DELAY)

    @Pyro4.expose
    def notify_processed_frame(self, headers):
        """Called by the pipeline daemon to notify that a new frame has completed processing
           headers is a dictionary holding the key-value pairs from the fits header"""
        print('Notified of a new frame:')
        for key in headers:
            print(key, headers[key])

    @Pyro4.expose
    def dome_control(self, automatic):
        """Switch the dome between manual (observer) and automatic (opsd) control"""
        with TryLock(self._command_lock) as success:
            if not success:
                return CommandStatus.Blocked

            # TODO: Require dome to be fully closed or open before switching to automatic
            if automatic and self._dome_mode == OperationsMode.Error:
                return CommandStatus.InErrorState

            self._dome_requested_mode = OperationsMode.Automatic if automatic else \
                OperationsMode.Manual

            observatory.log.info('opsd', 'Dome control manually changed to '
                                 + ('automatic' if automatic else 'manual'))

            return CommandStatus.Succeeded

    @Pyro4.expose
    def tel_control(self, automatic):
        """Switch the telescope between manual (observer) and automatic (opsd) control"""
        with TryLock(self._command_lock) as success:
            if not success:
                return CommandStatus.Blocked

            if automatic and self._tel_mode == OperationsMode.Error:
                return CommandStatus.InErrorState

            self._tel_requested_mode = OperationsMode.Automatic if automatic else \
                OperationsMode.Manual

            observatory.log.info('opsd', 'Telescope control manually changed to '
                                 + ('automatic' if automatic else 'manual'))

            return CommandStatus.Succeeded

    @Pyro4.expose
    def set_observing(self, observing):
        """Enable or disable the global observing mode (opens the dome)"""
        with TryLock(self._command_lock) as success:
            if not success:
                return CommandStatus.Blocked

            if observing and self._dome_mode == OperationsMode.Error:
                return CommandStatus.InErrorState

            self._observing = observing
            observatory.log.info('opsd', 'Observing condition manually '
                                 + 'enabled' if observing else 'disabled')

            return CommandStatus.Succeeded

    @Pyro4.expose
    def status(self):
        """Query the latest status."""
        data = {'observing': self._observing}

        with self._environment_lock:
            data.update({
                'environment_safe': self._environment_safe,
                'environment_updated': self._environment_updated.strftime('%Y-%m-%dT%H:%M:%SZ')
            })

        with self._dome_lock:
            data.update({
                'dome_mode': self._dome_mode,
                'dome_status': self._dome_status,
                'dome_updated': self._dome_updated.strftime('%Y-%m-%dT%H:%M:%SZ'),
                'dome_requested_mode': self._dome_requested_mode,
                'dome_requested_status': self._dome_requested_status
            })

        return data

if __name__ == '__main__':
    observatory.daemons.onemetre_operations.launch(OperationsDaemon())

